apiVersion: v1
kind: Pod

metadata: 
  name: nginxpod
  labels:
    app: nginx
    layer: front

spec:
  conatiners:
  - name: nginxcontainer
    imagePullPolicy: IfNotPresent
    image: nginx:1.16.1-alpine
    
--- 
apiVersion: v1
kind: Service

metadata:
  name: nginxservice
  labels:
    app: nginxservice
spec:
  selector:
    app: nginx
  ports:
  - port: 8888
    targetPort: 80
    protocol: TCP

---
apiVersion: apps/v1
kind: Deployments

metadata:
  name: nginxdeployment
  lables:
    app: deploynginxapps
spec:
  selector:
    app: nginx
  tempalte:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginxcontainer
        imagePullPolicy: IfNotPresent
        image: nginx:1.16.1-alpine
      